name: MTG Event Scraper

on:
  schedule:
    - cron: '5 12 * * 4'  # Jeudi à 12h05 UTC (soit 14h05 heure de Paris)
  workflow_dispatch:

jobs:
  scrape-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run bot script
        run: node bot.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
